[[redirects]]
  from = "/google_search/*"
  to = "https://anypr-17cbd4b4b7d1.herokuapp.com/google_search/:splat"
  status = 200
[[redirects]]
  from = "/.well-known/*"
  to = "https://anypr-17cbd4b4b7d1.herokuapp.com/.well-known/:splat"
  status = 200

[[headers]]
  for = "/*.yaml"
  [headers.values]
    Content-Type = "text/yaml"
